# Source: https://docs.github.com/es/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# Estas las proporcionan entidades terceras y las gobiernan
# condiciones de servicio, políticas de privacidad y documentación de soporte
# documentación.

name: Publish Python Package to TestPypi

# Publish only to TestPypi after bumping version (when closed Pull Requests to main)
on:
  workflow_run:
    workflows: ["Bump version"]
    types:
      - completed

jobs:
  deploy-testpypi:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          echo "funcionooooo"