
name: Test PR

# Bump version only when Pull Requests
on: pull_request

jobs:
  test-pr:

    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'SKIP')"

    steps:

    - name: echos
      env:
        COMMIT_MSG: ${{ github.event.head_commit.message }}
        HEAD_REF: ${{ github.event.pull_request.head.ref }}
        HEAD_REF_2: ${{ github.head_ref }}
      run: |
        echo ${COMMIT_MSG}
        echo ${HEAD_REF}
        echo ${HEAD_REF_2}
        echo ${GITHUB_BASE_REF}
        echo ${GITHUB_HEAD_REF}
        echo ${GITHUB_REF}
        echo "hooooola"
        echo "SKIPBUMP=TRUE" >> $GITHUB_ENV
