
name: Test

# Bump version only when Push
on: push

jobs:
  test:

    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'SKIP')"

    steps:
      - uses: actions/checkout@v3
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'poetry'


      - name: echos
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          REF_NAME: ${{ github.ref_name }}
          MY_ECHO: $(echo "heyeyeyey")
        run: |
          echo ${COMMIT_MSG}
          echo "hooooola"
          echo "SKIPBUMP=TRUE" >> $GITHUB_ENV
          echo ${REF_NAME}
          echo ${MY_ECHO}
          POETRY_VERSION=$(poetry version -s)
          echo "S{POETRY_VERSION}"
          echo "RELEASE_VERSION=${POETRY_VERSION}" >> $GITHUB_ENV
      - name: echo env
        env:
          skip_env: ${{ env.SKIPBUMP }}
          release_env: ${{ env.RELEASE_VERSION }}
        run: |
          echo ${skip_env}
          echo ${release_env}

