
name: Test

# Bump version only when Push
on: push

jobs:
  test:

    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'SKIP')"

    steps:

    - name: echos
      env:
        COMMIT_MSG: ${{ github.event.head_commit.message }}
        REF_NAME: ${{ github.ref_name }}
      run: |
        echo ${COMMIT_MSG}
        echo "hooooola"
        echo "SKIPBUMP=TRUE" >> $GITHUB_ENV
        echo ${REF_NAME}
