
name: Test

# Bump version only when Push
on: push

jobs:
  test:

    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'SKIP')"

    steps:

    #----------------------------------------------
    #  -----  install & configure poetry  -----
    #----------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8


    - name: echos
      env:
        COMMIT_MSG: ${{ github.event.head_commit.message }}
        REF_NAME: ${{ github.ref_name }}
        MY_ECHO: $(echo "heyeyeyey")
      run: |
        echo ${COMMIT_MSG}
        echo "hooooola"
        echo "SKIPBUMP=TRUE" >> $GITHUB_ENV
        echo ${REF_NAME}
        echo ${MY_ECHO}
        ls -a
        cd ..
        ls -a
        cd ..
        ls -a
        NEW_VERSION=$(poetry version -s)
        echo "NEW_VERSION"
